### ISSUE TITLE
build failure vs cups 2.3.0

### ISSUE THREAD

**Issue by dagbdagb** [matthiasbock/dymo-cups-drivers#11]
make bombs at:

depbase=`echo ../common/CupsPrintEnvironment.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../src  -I../common   -O2 -Wall -Wno-unknown-pragmas   -MT ../common/CupsPrintEnvironment.o -MD -MP -MF $depbase.Tpo -c -o ../common/CupsPrintEnvironment.o ../common/CupsPrintEnvironment.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../common/CupsPrintEnvironment.cpp: In member function ‘virtual void DymoPrinterDriver::CCupsPrintEnvironmentForLM::ReadData(DymoPrinterDriver::buffer_t&)’:
../common/CupsPrintEnvironment.cpp:139:23: error: ‘cupsBackChannelRead’ was not declared in this scope
   ssize_t bytesRead = cupsBackChannelRead((char*)buf, sizeof(buf), 2.5);
                       ^~~~~~~~~~~~~~~~~~~

Also see:
https://bugs.gentoo.org/693652

Also a fair number of warnings about deprecated functions when built with -Wdeprecated-declarations  .

**Comment by matthiasbock** [comment]
Thank you for your report. Unfortunately, I can't reproduce your problem. Also, it seems to me that other sources than mine were used in the linked bug report, so it's of little use to me. If you believe, the problem there also applies to this repository, please create a fresh clone of this repository and provide the full console output of all your compilation steps. Please also tell me your compiler versions. Thank you.

**Comment by jkl1337** [comment]
This repo is indeed affected when trying to build against cups 2.3.0. cups/sidechannel.h must be added explicility to CupsPrintEnvironment.cpp.

**Comment by matthiasbock** [comment]
Thank you, @jkl1337. Also to you: Please create a fresh clone of this repository and provide the full console output of your compilation process.

If you have a patch, please upload it here (the patch or the patched file) or kindly make a pull request.
