### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by villandra** [matthiasbock/dymo-cups-drivers#16]
I am installing dymo-cups-drivers-1.4.0.5 on Ubuntu 18.04.   I made sure all dependencies are installed.

I get as far as make.  

Someone previously posted the same problem and while the answer was not written in clear English it looked as though you fixed the problem.  If the answer is somethnig I'm supposed to do to the script please post the instructions IN DETAIL.  I'm a newbie.

Making all in src
make[1]: Entering directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src'
make  all-recursive
make[2]: Entering directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src'
Making all in lw
make[3]: Entering directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw'
Making all in tests
make[4]: Entering directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw/tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw/tests'
make[4]: Entering directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw'
g++ -DHAVE_CONFIG_H -I. -I../../src -I../common    -O2 -Wall -Wno-unknown-pragmas   -MT raster2dymolw.o -MD -MP -MF .deps/raster2dymolw.Tpo -c -o raster2dymolw.o raster2dymolw.cpp
In file included from raster2dymolw.cpp:37:0:
../common/CupsFilter.h: In member function ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**)’:
../common/CupsFilter.h:135:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<CHalftoneFilter> H;
          ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from raster2dymolw.cpp:28:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from raster2dymolw.cpp:37:0:
../common/CupsFilter.h: In member function ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*)’:
../common/CupsFilter.h:218:3: error: ‘ppd_file_t’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
   ^~~~~~~~~~
../common/CupsFilter.h:218:3: note: suggested alternative: ‘cups_file_t’
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
   ^~~~~~~~~~
   cups_file_t
../common/CupsFilter.h:218:15: error: ‘ppd’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
               ^~~
../common/CupsFilter.h:218:21: error: there are no arguments to ‘ppdOpenFile’ that depend on a template parameter, so a declaration of ‘ppdOpenFile’ must be available [-fpermissive]
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ^~~~~~~~~~~
../common/CupsFilter.h:218:21: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../common/CupsFilter.h:228:3: error: there are no arguments to ‘ppdMarkDefaults’ that depend on a template parameter, so a declaration of ‘ppdMarkDefaults’ must be available [-fpermissive]
   ppdMarkDefaults(ppd);
   ^~~~~~~~~~~~~~~
../common/CupsFilter.h:234:7: error: there are no arguments to ‘ppdMarkOption’ that depend on a template parameter, so a declaration of ‘ppdMarkOption’ must be available [-fpermissive]
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ^~~~~~~~~~~~~
../common/CupsFilter.h:238:3: error: there are no arguments to ‘cupsMarkOptions’ that depend on a template parameter, so a declaration of ‘cupsMarkOptions’ must be available [-fpermissive]
   cupsMarkOptions(ppd, OptionCount, Options);
   ^~~~~~~~~~~~~~~
../common/CupsFilter.h:243:3: error: ‘ppd_choice_t’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
   ^~~~~~~~~~~~
../common/CupsFilter.h:243:3: note: suggested alternative: ‘cups_cspace_t’
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
   ^~~~~~~~~~~~
   cups_cspace_t
../common/CupsFilter.h:243:17: error: ‘choice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                 ^~~~~~
../common/CupsFilter.h:243:17: note: suggested alternative: ‘clone’
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                 ^~~~~~
                 clone
../common/CupsFilter.h:243:26: error: there are no arguments to ‘ppdFindMarkedChoice’ that depend on a template parameter, so a declaration of ‘ppdFindMarkedChoice’ must be available [-fpermissive]
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ^~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:3: error: there are no arguments to ‘ppdClose’ that depend on a template parameter, so a declaration of ‘ppdClose’ must be available [-fpermissive]
   ppdClose(ppd);
   ^~~~~~~~
In file included from raster2dymolw.cpp:38:0:
CupsFilterLabelWriter.h: At global scope:
CupsFilterLabelWriter.h:36:89: error: ‘ppd_file_t’ has not been declared
 sPPDOptions (CLabelWriterDriver& Driver, CDummyLanguageMonitor& LM, ppd_file_t* ppd);
                                                                     ^~~~~~~~~~
CupsFilterLabelWriter.h:43:98: error: ‘ppd_file_t’ has not been declared
 ns (CLabelWriterDriverTwinTurbo& Driver, CDummyLanguageMonitor& LM, ppd_file_t* ppd);
                                                                     ^~~~~~~~~~
In file included from raster2dymolw.cpp:38:0:
CupsFilterLabelWriter.h:50:95: error: ‘ppd_file_t’ has not been declared
 tions (CLabelWriterDriver& Driver, CLabelWriterLanguageMonitor& LM, ppd_file_t* ppd);
                                                                     ^~~~~~~~~~
CupsFilterLabelWriter.h:58:104: error: ‘ppd_file_t’ has not been declared
 abelWriterDriverTwinTurbo& Driver, CLabelWriterLanguageMonitor& LM, ppd_file_t* ppd);
                                                                     ^~~~~~~~~~
raster2dymolw.cpp: In function ‘int main(int, char**)’:
raster2dymolw.cpp:60:3: error: ‘ppd_file_t’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
   ^~~~~~~~~~
raster2dymolw.cpp:60:3: note: suggested alternative: ‘cups_file_t’
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
   ^~~~~~~~~~
   cups_file_t
raster2dymolw.cpp:60:15: error: ‘ppd’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
               ^~~
raster2dymolw.cpp:60:21: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ^~~~~~~~~~~
In file included from raster2dymolw.cpp:37:0:
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriver; DI = DymoPrinterDriver::CDriverInitializerLabelWriterWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriver; DI = DymoPrinterDriver::CDriverInitializerLabelWriterWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’
raster2dymolw.cpp:68:35:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriver; DI = DymoPrinterDriver::CDriverInitializerLabelWriter; LM = DymoPrinterDriver::CDummyLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriver; DI = DymoPrinterDriver::CDriverInitializerLabelWriter; LM = DymoPrinterDriver::CDummyLanguageMonitor]’
raster2dymolw.cpp:73:35:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriverTwinTurbo; DI = DymoPrinterDriver::CDriverInitializerLabelWriterTwinTurboWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriverTwinTurbo; DI = DymoPrinterDriver::CDriverInitializerLabelWriterTwinTurboWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’
raster2dymolw.cpp:84:37:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriverTwinTurbo; DI = DymoPrinterDriver::CDriverInitializerLabelWriterTwinTurbo; LM = DymoPrinterDriver::CDummyLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriverTwinTurbo; DI = DymoPrinterDriver::CDriverInitializerLabelWriterTwinTurbo; LM = DymoPrinterDriver::CDummyLanguageMonitor]’
raster2dymolw.cpp:89:37:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriver400; DI = DymoPrinterDriver::CDriverInitializerLabelWriterWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriver400; DI = DymoPrinterDriver::CDriverInitializerLabelWriterWithLM; LM = DymoPrinterDriver::CLabelWriterLanguageMonitor]’
raster2dymolw.cpp:103:37:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
../common/CupsFilter.h: In instantiation of ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*) [with D = DymoPrinterDriver::CLabelWriterDriver400; DI = DymoPrinterDriver::CDriverInitializerLabelWriter; LM = DymoPrinterDriver::CDummyLanguageMonitor]’:
../common/CupsFilter.h:99:15:   required from ‘int DymoPrinterDriver::CCupsFilter<D, DI, LM>::Run(int, char**) [with D = DymoPrinterDriver::CLabelWriterDriver400; DI = DymoPrinterDriver::CDriverInitializerLabelWriter; LM = DymoPrinterDriver::CDummyLanguageMonitor]’
raster2dymolw.cpp:108:37:   required from here
../common/CupsFilter.h:218:32: error: ‘ppdOpenFile’ was not declared in this scope
   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
../common/CupsFilter.h:228:18: error: ‘ppdMarkDefaults’ was not declared in this scope
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
../common/CupsFilter.h:228:18: note: suggested alternative: ‘cupsLangDefault’
   ppdMarkDefaults(ppd);
   ~~~~~~~~~~~~~~~^~~~~
   cupsLangDefault
../common/CupsFilter.h:234:20: error: ‘ppdMarkOption’ was not declared in this scope
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:234:20: note: suggested alternative: ‘cupsParseOptions’
       ppdMarkOption(ppd, Options[i].name, Options[i].value);
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       cupsParseOptions
../common/CupsFilter.h:238:18: error: ‘cupsMarkOptions’ was not declared in this scope
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:238:18: note: suggested alternative: ‘cupsParseOptions’
   cupsMarkOptions(ppd, OptionCount, Options);
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cupsParseOptions
../common/CupsFilter.h:243:45: error: ‘ppdFindMarkedChoice’ was not declared in this scope
   ppd_choice_t* choice = ppdFindMarkedChoice(ppd, "DymoHalftoning");
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../common/CupsFilter.h:248:11: error: ‘ppdClose’ was not declared in this scope
   ppdClose(ppd);
   ~~~~~~~~^~~~~
../common/CupsFilter.h:248:11: note: suggested alternative: ‘pclose’
   ppdClose(ppd);
   ~~~~~~~~^~~~~
   pclose
Makefile:345: recipe for target 'raster2dymolw.o' failed
make[4]: *** [raster2dymolw.o] Error 1
make[4]: Leaving directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw'
Makefile:435: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src/lw'
Makefile:262: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src'
Makefile:204: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dora/dymo/dymo-cups-drivers-1.4.0.5/src'
Makefile:263: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by villandra** [comment]
I suspect the problem is I used the origional version from the Dymo web site which this author fixed.

But I need complete instructions on how to download and install his version.   I read the readme file, it's exactly as clear as mud.

Starting please with how to git the file.

Then how do I get to where I compile it.        

All that is in the readme file is a list of stray commands with no idea what to do with them, and no idea ow to download the code to compile.

**Comment by villandra** [comment]
Here we go.  En Ingles.    That's, INGLES.  Like, people can comprehend it.

install cups, git, autotools (actually three other things that comprise autotools), GCC and their dependencies.  Might be more dependencies, can't recall by the time I've been through it all.  

git clone https://github.com/matthiasbock/dymo-cups-drivers.git
cd dymo-cups-drivers
./build.sh
./configure
make
sudo make install

MUCHO simple.  Honestly!

Haven't tested to make sure it works so don't know if there's something more.

**Comment by matthiasbock** [comment]
Please keep comments friendly and objective. Thank you.

For build instructions, please refer to the [Build instructions](../blob/master/README.md#build-instructions).
