### ISSUE TITLE
Support for Dymo LabelWritter 550 Turbo

### ISSUE THREAD

**Issue by jmarino** [matthiasbock/dymo-cups-drivers#18]
Are there any plans add support for Dymo LabelWritter 550 Turbo. They are discontinuing the 450 Turbo, and the 550 Turbo is the replacement.

I was able to get the ppd file (lw550t.ppd) from Dymo's mac drivers package: https://s3.amazonaws.com/download.dymo.com/dymo/Software/Mac/DCDMac1.4.3.103.pkg

It's not all that different from the lw450t.ppd, however, this ppd appears to use a new version of `raster2dymolw`. I have no idea what's different about it.

**Comment by jmarino** [comment]
I can do one better! I found this github repo [dymosoftware/Drivers](https://github.com/dymosoftware/Drivers) that seems to be provided by the Dymo company. Inside, under folder [LW5xx Linux 1.4.3](https://github.com/dymosoftware/Drivers/tree/main/LW5xx%20Linux%201.4.3) they have a zip file with the drivers for the 550x family of printers.

This zip file includes the 550x ppd files and the code for the V2 versions of the filters raster2dymolm and raster2dymolw (they build binaries with suffix _v2).

I have compiled the drivers, installed the raster2dymolw_v2 and lw550t.ppd files by hand and I can verify that they work.

**Comment by matthiasbock** [comment]
Great! Thank you very much for pointing this out and for confirming that it works!

As soon as I find some time will merge the changes here...

**Comment by jmarino** [comment]
I need to integrate this also. I'll see if I can do it on my end and send a PR your way.

**Comment by Chick92** [comment]
Are you able to make the above changes to this repo? I'm happy to test on a 550 I just bought.

**Comment by jmarino** [comment]
@Chick92 I created a PR with the code (PR #19). If you add my forked repo to your remotes and checkout the PR branch, you should be able to test things.

**Comment by matthiasbock** [comment]
I merged PR #19 with commit 087832e, compilation is fixed in 4b88db7.

**Comment by jmarino** [comment]
@Chick92 The PR got merged. Can you confirm that the new drivers work with the new 550 printers?

**Comment by matthiasbock** [comment]
No more complaints, so I assume it works :-)
