### ISSUE TITLE
GitHub Flow doesn't work

### ISSUE THREAD

**Issue by frankhommers** [matthiasbock/dymo-cups-drivers#20]
The first message I get when I trigger the build github action is:

```
In file included from raster2dymolw.cpp:37:
../common/CupsFilter.h: In member function ‘void DymoPrinterDriver::CCupsFilter<D, DI, LM>::InitDocument(const char*)’:
../common/CupsFilter.h:219:46: warning: ‘ppd_file_t* ppdOpenFile(const char*)’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
  219 |   ppd_file_t* ppd = ppdOpenFile(getenv("PPD"));
      |                                              ^

```

**Comment by matthiasbock** [comment]
That's a warning, not an error. The "GitHub Flow" i.e. the compilation works, as can be seen in the "Actions" tab.
It warns that functions are used, that have been declared deprecated in CUPS.
If those warnings disturb you, feel free to update the deprecated function calls and open a pull request.
Best, Matthias
