### ISSUE TITLE
Does this present the dymo label printer as a printer to the Dymo software on another machine running Windows/Linux?

### ISSUE THREAD

**Issue by thestraycat** [matthiasbock/dymo-cups-drivers#30]
As above really...

Is this project purely for sending print commands over the network through a terminal shell to the printer?
Or will it allow a remote windows or linux client running the dymo studio design software, to add/print from the remotely attached dymo printer?

**Comment by matthiasbock** [comment]
This repository implements driver(s) which enable printing on locally connected Dymo printers.
You can set up your printer via CUPS to enable printing via the network.

I am aware, that the Dymo software offers networking printing,
i.e. printing on a Dymo printer, which is attached to another machine
(which must concurrently run the Dymo software, I guess?).
However, it is proprietary software and I do not know,
what kind of network protocol it uses (if you know more, feel free to let me know).
Hence, there is no support for network printing from Dymo software here.

Best, Matthias
