### ISSUE TITLE
Cups Error: APPrinterIconPath: No such file or directory

### ISSUE THREAD

**Issue by GHPS** [matthiasbock/dymo-cups-drivers#9]
While working an PR https://github.com/matthiasbock/dymo-cups-drivers/pull/8 I took a second look at Cups' error.log and
stumbled upon this recurring entry:

> unknown: File \"/Library/Printers/DYMO/CUPS/Resources/LM400.icns\" not available:
> No such file or directory

On linux the Cups system throws this error every time the PPD file is
accessed. The cause for the error is this line:

` *APPrinterIconPath: "/Library/Printers/DYMO/CUPS/Resources/LM400.icns"`

The APPrinterIconPath function is a Cups extension used on MacOS, specifying
an icon (in Apple's icns format) present only in MacOS [1]. Therefore, Cups
complains about a missing file - which would be useless in Linux
even if the file was available.

The problem has obviously arisen when Dymo decided to use the same PPD files
on Linux and MacOS systems. This somehow worked but has side effects, i.e.
error messages gone astray.

Since this is the Linux driver I suggest deleting all references to 
APPrinterIconPath in all included PPD files.

1:https://www.cups.org/doc/spec-ppd.html#APPrinterIconPath

**Comment by matthiasbock** [comment]
I agree. Are you planning on preparing a pull request for that?

**Comment by GHPS** [comment]
Done, see PR https://github.com/matthiasbock/dymo-cups-drivers/pull/10
